os: linux
dist: xenial

jobs:
    include:
        - language: go
          go:
            - "1.13.x"
          install:
            - go get -t -v ./...
          script:
            - go test -v ./...
        - language: minimal
          services:
            - docker
          install:
              - docker pull golang:alpine
              - docker pull alpine
          script:
              - docker build -t tkw1536/proxyssh:simple -f Dockerfile.simple .
              - docker build -t tkw1536/proxyssh -f Dockerfile .

